### ISSUE TITLE
If ENV variables aren't set, hostctl panics

### ISSUE THREAD

**Issue by TheNathanBlack** [gliderlabs/hostctl#5]
With my environment set like this:

``` bash
Black-Company:hostctl nathan$ ./hostctl env
HOSTCTL_NAME=""                          # optional default name
HOSTCTL_PROVIDER="digitalocean"          # cloud provider
HOSTCTL_IMAGE=""                         # vm image
HOSTCTL_FLAVOR=""                        # vm flavor
HOSTCTL_REGION=""                        # vm region
HOSTCTL_KEYNAME=""                       # vm keyname
HOSTCTL_USER="nathan"                    # ssh user
HOSTCTL_NAMESPACE=""                     # optional namespace for names
HOSTCTL_USERDATA=""                      # vm user data
DO_TOKEN="XXXXXXXXXXXXXXXX0c08"          # token for DigitalOcean API v2
```

When I attempt to `hostctl up` I get this response:

``` bash
Black-Company:hostctl nathan$ ./hostctl up
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
    panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x25cd]

goroutine 1 [running]:
text/template.errRecover(0xc208063ac8)
    /usr/local/go/src/text/template/exec.go:100 +0xbc
main.(*Context).Write(0xc208058420, 0xc20802a890, 0x8, 0x8, 0xc20805a501, 0x0, 0x0)
    /Users/nathan/dev/go/src/github.com/gliderlabs/hostctl/cmd.go:71 +0x6d
text/template.(*state).walk(0xc20803a940, 0x386100, 0xc208035380, 0x16, 0x6170d0, 0xc20803d080)
    /usr/local/go/src/text/template/exec.go:182 +0x343
text/template.(*state).walk(0xc20803a940, 0x386100, 0xc208035380, 0x16, 0x617310, 0xc20803cf00)
    /usr/local/go/src/text/template/exec.go:175 +0x862
text/template.(*Template).Execute(0xc20803a200, 0x617018, 0xc208058420, 0x386100, 0xc208035380, 0x0, 0x0)
    /usr/local/go/src/text/template/exec.go:155 +0x3f2
github.com/spf13/cobra.tmpl(0x617018, 0xc208058420, 0x4449f0, 0x34e, 0x386100, 0xc208035380, 0x0, 0x0)
    /Users/nathan/dev/go/src/github.com/spf13/cobra/cobra.go:111 +0x36c
github.com/spf13/cobra.func·003(0xc208035380, 0x0, 0x0)
    /Users/nathan/dev/go/src/github.com/spf13/cobra/command.go:178 +0xbb
github.com/spf13/cobra.(*Command).Usage(0xc208035380, 0x0, 0x0)
    /Users/nathan/dev/go/src/github.com/spf13/cobra/command.go:678 +0x5b
main.func·009(0xc208058420)
    /Users/nathan/dev/go/src/github.com/gliderlabs/hostctl/up.go:20 +0x8f
main.func·010(0xc208035380, 0x55c960, 0x0, 0x0)
    /Users/nathan/dev/go/src/github.com/gliderlabs/hostctl/cmd.go:50 +0x164
github.com/spf13/cobra.(*Command).execute(0xc208035380, 0x55c960, 0x0, 0x0, 0x0, 0x0)
    /Users/nathan/dev/go/src/github.com/spf13/cobra/command.go:477 +0x3d4
github.com/spf13/cobra.(*Command).Execute(0xc208034820, 0x0, 0x0)
    /Users/nathan/dev/go/src/github.com/spf13/cobra/command.go:551 +0x414
main.(*Command).Execute(0x550e60, 0x0, 0x0)
    /Users/nathan/dev/go/src/github.com/gliderlabs/hostctl/cmd.go:23 +0x4c
main.main()
    /Users/nathan/dev/go/src/github.com/gliderlabs/hostctl/hostctl.go:34 +0x124
```

It should probably warn that required values were not set.

**Comment by TheNathanBlack** [comment]
Fixed by @progrium in efa5240ef476d94c27729384b4c38311499e2f46
